apiVersion: v1
kind: Secret

metadata:
  name: {{ include "nginx.fullname" . }}-secret

  labels:
    {{- include "nginx.labels" . | nindent 4 }}

type: Opaque

stringData:
  DB_USERNAME: admin
  DB_PASSWORD: password123 